language: python
python:
        - "3.5"
        - "3.6"

install:
        - pip install pyparsing lxml pytest flake8 pylint hypothesis

script: pytest tests

jobs:
        include:
                - stage: code style
                  script: pylint --extension-pkg-whitelist=lxml src
stages:
        - test
        - code style
