language: python
python:
        - "3.5"
        - "3.6"

install:
        - pip install pyparsing pytest flake8 pylint hypothesis

jobs:
        include:
                - script: pytest tests
                - script: pytest tests
                  python: "3.6"
                - stage: code style
                  script: pylint src
stages:
        - test
        - code style
